springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

server:
  servlet:
    session:
      cookie:
        secure: true

app:
  deployment:
    production: true
    trusted-proxy-cidrs: ${TRUSTED_PROXY_CIDRS}
  security:
    cookie:
      secure: true
