/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/proposals/{publicId}/support": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 제안 동의
         * @description 중복 요청을 멱등 처리하고 DB 유효 동의 수로 정식 안건 승격을 판단합니다.
         */
        put: operations["support"];
        post?: never;
        /**
         * 제안 동의 철회
         * @description 동의 모집 중에만 본인의 동의를 멱등적으로 철회합니다.
         */
        delete: operations["withdrawSupport"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 제안 피드
         * @description 학생은 공개 제안을, 교사는 정식 안건 이후 제안만 조회합니다.
         */
        get: operations["list"];
        put?: never;
        /**
         * 공개 제안 등록
         * @description 익명 또는 실명 공개를 선택하고 작성자 자동 동의 1표를 함께 저장합니다.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{publicId}/review-start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 담당 교사 검토 시작 */
        post: operations["startReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{publicId}/review-resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 보류 안건 검토 재개 */
        post: operations["resumeReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{publicId}/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 제안 신고
         * @description 같은 사용자의 같은 제안 신고는 멱등 처리하며 신고만으로 공개 상태는 바뀌지 않습니다.
         */
        post: operations["report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{publicId}/execution-start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 채택 안건 실행 시작과 공식 업데이트 */
        post: operations["startExecution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{publicId}/execution-complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 안건 실행 완료와 공식 업데이트 */
        post: operations["completeExecution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{publicId}/decisions/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 정식 안건 반려와 공식 답변 */
        post: operations["reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{publicId}/decisions/hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 정식 안건 보류와 공식 답변 */
        post: operations["hold"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{publicId}/decisions/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 정식 안건 채택과 공식 답변 */
        post: operations["accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/moderation/reports/{reportPublicId}/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 분리 심의 사건 생성
         * @description 현임 학생부장이 현재 세 직책 담당자를 사건 심의자로 고정합니다.
         */
        post: operations["createCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/moderation/cases/{publicId}/votes/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 심의 반대
         * @description 한 명이라도 반대하면 사건이 반려됩니다.
         */
        post: operations["reject_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/moderation/cases/{publicId}/votes/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 심의 승인
         * @description 세 명 모두 승인하면 사건이 승인됩니다.
         */
        post: operations["approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/identity-reveal-cases/{publicId}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 작성자 신원 일회 확인
         * @description 승인 사건의 학생부장이 최근 재인증 후 한 번만 확인할 수 있습니다.
         */
        post: operations["reveal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reauthenticate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 최근 재인증
         * @description 민감한 관리 작업 전에 현재 비밀번호를 다시 확인합니다.
         */
        post: operations["reauthenticate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 비밀번호 재설정 완료
         * @description 일회용 재설정 코드를 소비하고 기존 세션을 모두 폐기합니다.
         */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 현재 서버 세션과 세션·CSRF 쿠키를 무효화합니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 계정/IP 영속 제한을 확인하고 새 MySQL 세션을 발급합니다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 최초 계정 활성화
         * @description 개인별 일회용 가입 코드를 소비하고 Argon2id 비밀번호를 설정합니다.
         */
        post: operations["activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 계정 검색
         * @description 로그인 ID·표시 이름과 상태로 계정을 검색하고 현재 역할·보직을 조회합니다.
         */
        get: operations["list_1"];
        put?: never;
        /**
         * 계정 생성
         * @description 활성화 대기 계정과 역할을 만들고 가입 코드를 한 번만 반환합니다.
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{publicId}/suspensions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 계정 정지
         * @description 활성 계정을 정지하고 해당 계정의 모든 서버 세션을 폐기합니다.
         */
        post: operations["suspend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{publicId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 역할 임기 추가
         * @description 기존 이력을 덮어쓰지 않고 기간이 겹치지 않는 역할 임기를 추가합니다.
         */
        post: operations["assignRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{publicId}/roles/{role}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 역할 임기 종료
         * @description 지정 시각을 포함하는 역할 임기를 종료하고 변경 사유를 보존합니다.
         */
        post: operations["endRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{publicId}/reactivations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 계정 재활성화
         * @description 정지 계정을 기존 자격 증명으로 다시 활성화합니다.
         */
        post: operations["reactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{publicId}/password-reset-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 비밀번호 재설정 코드 발급
         * @description 이전 미사용 코드를 폐기하고 새 코드를 한 번만 반환합니다.
         */
        post: operations["issuePasswordResetCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{publicId}/activation-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 가입 코드 재발급
         * @description 이전 미사용 코드를 폐기하고 새 코드를 한 번만 반환합니다.
         */
        post: operations["reissueActivationCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/proposals/{publicId}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 정식 안건 담당 교사 지정
         * @description 기존 담당은 종료 이력으로 보존하고 새 담당을 내부 지정합니다.
         */
        post: operations["assign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/offices/{office}/users/{publicId}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 보직 임기 종료
         * @description 지정 사용자와 시각에 해당하는 보직 임기를 종료합니다.
         */
        post: operations["end"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/offices/{office}/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 보직 임명·예약
         * @description 필요 역할과 기간 중복을 검증하고 후임 교체를 원자적으로 처리합니다.
         */
        post: operations["appoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API 상태 확인
         * @description 인증 없이 API 프로세스와 서버 기준 시각을 확인합니다. 데이터베이스 준비 상태는 운영용 health 상세 정책과 분리합니다.
         */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 제안 상세
         * @description 교사에게는 정식 안건 이후 제안만 존재하는 것으로 공개합니다.
         */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/moderation/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 신고 사건함
         * @description 현임 학생부장에게만 신고 내용과 제안 본문을 제공합니다.
         */
        get: operations["reports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/moderation/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 심의 사건 목록
         * @description 사건 생성 시 고정된 심의자에게만 해당 사건을 제공합니다.
         */
        get: operations["cases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/moderation/cases/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 심의 사건 상세 */
        get: operations["caseDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 현재 사용자
         * @description 세션에 연결된 공개 계정 정보와 현재 역할·보직을 반환합니다.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * CSRF 토큰 발급
         * @description 로그인 전을 포함해 상태 변경 요청 전에 호출합니다.
         */
        get: operations["csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{publicId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 계정 상세
         * @description 계정 상태와 덮어쓰지 않은 역할·보직 임기 이력을 조회합니다.
         */
        get: operations["get_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 담당 지정용 정식 안건 목록
         * @description 본문 없이 제목·상태와 내부 담당 정보만 반환합니다.
         */
        get: operations["list_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/proposals/eligible-teachers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 담당 지정 가능한 활성 교사 목록 */
        get: operations["teachers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 공통 API 오류 */
        ErrorResponse: {
            /** @example VALIDATION_FAILED */
            code: string;
            /** @example 요청 값을 확인해 주세요. */
            message: string;
            /** Format: date-time */
            timestamp: string;
            /** @description 요청 상관관계 ID. 세션 또는 사용자 식별자가 아님 */
            traceId: string;
            fieldErrors?: components["schemas"]["FieldErrorResponse"][];
        };
        /** @description 동의 명령 이후 서버가 다시 계산한 상태 */
        SupportResponse: {
            supported: boolean;
            /** Format: int32 */
            supportCount: number;
            /** Format: int32 */
            supportThreshold: number;
            workflowStatus: string;
            justFormalized: boolean;
        };
        /** @description 학생 공개 제안 작성 */
        CreateProposalRequest: {
            title: string;
            content: string;
            /** @enum {string} */
            authorVisibility: "ANONYMOUS" | "NAMED";
        };
        /** @description 권한에 따라 공개되는 제안 상세 */
        ProposalDetailResponse: {
            /** Format: uuid */
            publicId: string;
            title: string;
            content: string;
            authorVisibility: string;
            authorDisplayName?: string;
            workflowStatus: string;
            visibilityStatus: string;
            /** Format: int32 */
            supportCount: number;
            /** Format: int32 */
            supportThreshold: number;
            viewerSupported: boolean;
            /** @description 현재 조회자가 내부 지정된 활성 담당 교사인지 여부 */
            viewerCanManage?: boolean;
            /** Format: date-time */
            formalizedAt?: string;
            /** Format: int32 */
            formalizedSupportCount?: number;
            /** Format: date-time */
            createdAt: string;
            statusHistory: components["schemas"]["ProposalStatusHistoryResponse"][];
            officialResponses: components["schemas"]["ProposalOfficialResponseResponse"][];
        };
        /** @description 학생과 교사에게 공개되는 학교 공식 답변. 응답 교사의 식별 정보는 포함하지 않습니다. */
        ProposalOfficialResponseResponse: {
            resultingStatus?: string;
            content?: string;
            decisionReason?: string;
            followUpPlan?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description 덮어쓰지 않는 제안 업무 상태 이력 */
        ProposalStatusHistoryResponse: {
            fromStatus?: string;
            toStatus: string;
            /** Format: int32 */
            supportCountSnapshot?: number;
            reason: string;
            /** Format: date-time */
            createdAt: string;
        };
        ProposalTransitionReasonRequest: {
            reason: string;
        };
        ProposalWorkflowResponse: {
            workflowStatus?: string;
        };
        ContentReportRequest: {
            reason: string;
        };
        ContentReportResponse: {
            /** Format: uuid */
            publicId?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        OfficialResponseRequest: {
            content: string;
            decisionReason: string;
            followUpPlan?: string;
        };
        CreateModerationCaseRequest: {
            /** @enum {string} */
            caseType: "CONTENT_VISIBILITY" | "IDENTITY_REVEAL";
            reason: string;
        };
        ModerationCaseResponse: {
            /** Format: uuid */
            publicId?: string;
            caseType?: string;
            caseStatus?: string;
            /** Format: uuid */
            proposalPublicId?: string;
            proposalTitle?: string;
            proposalContent?: string;
            authorVisibility?: string;
            authorDisplayName?: string;
            sourceReportReason?: string;
            caseReason?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            decidedAt?: string;
            viewerOffice?: string;
            viewerVoted?: boolean;
            identityRevealed?: boolean;
            votes?: components["schemas"]["ModerationVoteResponse"][];
        };
        ModerationVoteResponse: {
            office?: string;
            decision?: string;
            reason?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        ModerationVoteRequest: {
            reason: string;
        };
        ModerationVoteResultResponse: {
            caseStatus?: string;
        };
        IdentityRevealRequest: {
            reason: string;
        };
        IdentityRevealResponse: {
            loginId?: string;
            displayName?: string;
            /** Format: date-time */
            revealedAt?: string;
        };
        /** @description 민감 작업 전 최근 재인증 요청 */
        ReauthenticationRequest: {
            /**
             * Format: password
             * @example correct horse battery staple
             */
            password: string;
        };
        /** @description 현재 로그인 사용자에게 공개 가능한 계정 정보 */
        CurrentUserResponse: {
            /** Format: uuid */
            publicId: string;
            loginId: string;
            displayName: string;
            roles: string[];
            offices: string[];
            /** Format: date-time */
            reauthenticatedAt: string;
            /** Format: date-time */
            reauthenticationExpiresAt: string;
        };
        /** @description 일회용 코드로 비밀번호 재설정 */
        PasswordResetRequest: {
            /** @example student.2026 */
            loginId: string;
            /**
             * @description 관리자에게 안전한 경로로 전달받은 일회용 코드
             * @example G8vY4mN7qR2x
             */
            resetCode: string;
            /**
             * Format: password
             * @example new correct horse battery staple
             */
            newPassword: string;
        };
        /** @description 자체 계정 로그인 요청 */
        LoginRequest: {
            /** @example student.2026 */
            loginId: string;
            /**
             * Format: password
             * @example correct horse battery staple
             */
            password: string;
        };
        /** @description 입력 필드 검증 오류 */
        FieldErrorResponse: {
            /** @example title */
            field?: string;
            /** @example 제목을 입력해 주세요. */
            reason?: string;
        };
        /** @description 최초 계정 활성화 요청 */
        ActivationRequest: {
            /** @example student.2026 */
            loginId: string;
            /**
             * @description 관리자에게 안전한 경로로 전달받은 일회용 코드
             * @example 7Kp9zT4Wh3Nm
             */
            activationCode: string;
            /**
             * Format: password
             * @example correct horse battery staple
             */
            password: string;
        };
        /** @description 활성화 대기 계정 생성 */
        CreateAccountRequest: {
            /** @example student.2026 */
            loginId: string;
            /** @example 홍길동 */
            displayName: string;
            /** @enum {string} */
            role: "STUDENT" | "TEACHER" | "SUPER_ADMIN";
            /** @example 2026학년도 학생 계정 등록 */
            reason: string;
        };
        /** @description 한 번만 표시되는 계정 코드. 응답을 로그·브라우저 저장소에 보관하지 않습니다. */
        OneTimeCodeResponse: {
            /** Format: uuid */
            userPublicId?: string;
            /** @example 7Kp9zT4Wh3NmQ6Rx */
            code?: string;
            /** Format: date-time */
            expiresAt?: string;
        };
        ReasonRequest: {
            /** @example 계정 도용 신고 확인 */
            reason: string;
        };
        /** @description 기본 계정 역할 임기 추가 */
        RoleAssignmentRequest: {
            /** @enum {string} */
            role: "STUDENT" | "TEACHER" | "SUPER_ADMIN";
            /**
             * Format: date-time
             * @description 비우면 서버 현재 시각에 즉시 시작
             */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            reason: string;
        };
        /** @description 저장된 역할 또는 보직 임기 */
        AssignmentPeriodResponse: {
            type: string;
            /** Format: date-time */
            startsAt: string;
            /** Format: date-time */
            endsAt?: string;
        };
        /** @description 역할 또는 보직 임기 종료 */
        EndAssignmentRequest: {
            /**
             * Format: date-time
             * @description 비우면 서버 현재 시각에 즉시 종료
             */
            endsAt?: string;
            reason: string;
        };
        AssignProposalTeacherRequest: {
            /** Format: uuid */
            teacherPublicId: string;
            reason: string;
        };
        /** @description 슈퍼 어드민 전용 정식 안건 담당 교사 정보 */
        ProposalAssignmentResponse: {
            /** Format: uuid */
            teacherPublicId?: string;
            teacherDisplayName?: string;
            /** Format: date-time */
            assignedAt?: string;
        };
        /** @description 임기 기반 보직 임명 또는 후임 예약 */
        OfficeAppointmentRequest: {
            /** Format: uuid */
            userPublicId: string;
            /**
             * Format: date-time
             * @description 비우면 서버 현재 시각에 즉시 시작
             */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            /** @description 시작 시점과 겹치는 현임자의 임기를 자동 종료 */
            replaceExistingAtStart?: boolean;
            reason: string;
        };
        /** @description API 실행 상태 */
        SystemStatusResponse: {
            /** @example ok */
            status?: string;
            /** Format: date-time */
            serverTime?: string;
            /** @example v1 */
            apiVersion?: string;
        };
        /** @description 접근 권한이 적용된 제안 피드 */
        ProposalPageResponse: {
            items: components["schemas"]["ProposalSummaryResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        /** @description 공개 제안 목록 항목 */
        ProposalSummaryResponse: {
            /** Format: uuid */
            publicId: string;
            title: string;
            excerpt: string;
            authorVisibility: string;
            authorDisplayName?: string;
            workflowStatus: string;
            visibilityStatus: string;
            /** Format: int32 */
            supportCount: number;
            /** Format: int32 */
            supportThreshold: number;
            viewerSupported: boolean;
            /** Format: date-time */
            formalizedAt?: string;
            /** Format: int32 */
            formalizedSupportCount?: number;
            /** Format: date-time */
            createdAt: string;
        };
        ReportInboxItemResponse: {
            /** Format: uuid */
            publicId?: string;
            /** Format: uuid */
            proposalPublicId?: string;
            proposalTitle?: string;
            proposalContent?: string;
            reason?: string;
            /** Format: date-time */
            createdAt?: string;
            existingCaseTypes?: string[];
        };
        CsrfToken: {
            headerName?: string;
            parameterName?: string;
            token?: string;
        };
        /** @description 상태 변경 요청에 사용할 CSRF 토큰 */
        CsrfTokenResponse: {
            headerName: string;
            parameterName: string;
            token: string;
        };
        /** @description 슈퍼 어드민용 계정 검색 결과 */
        AccountPageResponse: {
            items: components["schemas"]["AccountSummaryResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            totalElements: number;
            /** Format: int32 */
            totalPages: number;
        };
        /** @description 계정 목록에 표시되는 현재 상태 요약 */
        AccountSummaryResponse: {
            /** Format: uuid */
            publicId: string;
            loginId: string;
            displayName: string;
            status: string;
            currentRoles: string[];
            currentOffices: string[];
            /** Format: date-time */
            createdAt: string;
        };
        /** @description 슈퍼 어드민에게 공개되는 계정 상태와 역할·보직 이력 */
        AccountDetailResponse: {
            /** Format: uuid */
            publicId: string;
            loginId: string;
            displayName: string;
            status: string;
            roles: components["schemas"]["RoleAssignmentHistoryResponse"][];
            offices: components["schemas"]["OfficeAssignmentHistoryResponse"][];
        };
        OfficeAssignmentHistoryResponse: {
            office?: string;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            /** Format: date-time */
            assignedAt?: string;
            reason?: string;
            /** Format: date-time */
            endedAt?: string;
            endReason?: string;
        };
        RoleAssignmentHistoryResponse: {
            role?: string;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            endsAt?: string;
            /** Format: date-time */
            assignedAt?: string;
            reason?: string;
            /** Format: date-time */
            endedAt?: string;
            endReason?: string;
        };
        AdminProposalSummaryResponse: {
            /** Format: uuid */
            publicId?: string;
            title?: string;
            workflowStatus?: string;
            /** Format: date-time */
            formalizedAt?: string;
            assignment?: components["schemas"]["ProposalAssignmentResponse"];
        };
        EligibleProposalTeacherResponse: {
            /** Format: uuid */
            publicId?: string;
            displayName?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    support: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupportResponse"];
                };
            };
        };
    };
    withdrawSupport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SupportResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                scope?: "ALL" | "FORMAL_AGENDA";
                sort?: "LATEST" | "MOST_SUPPORTED";
                query?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProposalPageResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProposalRequest"];
            };
        };
        responses: {
            /** @description 제안과 첫 동의 생성 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProposalDetailResponse"];
                };
            };
        };
    };
    startReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalTransitionReasonRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProposalWorkflowResponse"];
                };
            };
        };
    };
    resumeReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalTransitionReasonRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProposalWorkflowResponse"];
                };
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContentReportRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ContentReportResponse"];
                };
            };
        };
    };
    startExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfficialResponseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProposalWorkflowResponse"];
                };
            };
        };
    };
    completeExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfficialResponseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProposalWorkflowResponse"];
                };
            };
        };
    };
    reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfficialResponseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProposalWorkflowResponse"];
                };
            };
        };
    };
    hold: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfficialResponseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProposalWorkflowResponse"];
                };
            };
        };
    };
    accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfficialResponseRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProposalWorkflowResponse"];
                };
            };
        };
    };
    createCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportPublicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateModerationCaseRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ModerationCaseResponse"];
                };
            };
        };
    };
    reject_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerationVoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ModerationVoteResultResponse"];
                };
            };
        };
    };
    approve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModerationVoteRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ModerationVoteResultResponse"];
                };
            };
        };
    };
    reveal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityRevealRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IdentityRevealResponse"];
                };
            };
        };
    };
    reauthenticate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReauthenticationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 로그인 성공과 새 서버 세션 발급 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description 입력 검증 실패 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 자격 증명 또는 계정 상태 확인 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description CSRF 검증 실패 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 계정 또는 IP 로그인 제한 */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    activate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivationRequest"];
            };
        };
        responses: {
            /** @description 활성화 완료 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                query?: string;
                status?: "PENDING_ACTIVATION" | "ACTIVE" | "SUSPENDED" | "DEACTIVATED";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountPageResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccountRequest"];
            };
        };
        responses: {
            /** @description 계정과 가입 코드 생성 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OneTimeCodeResponse"];
                };
            };
        };
    };
    suspend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    assignRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleAssignmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AssignmentPeriodResponse"];
                };
            };
        };
    };
    endRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
                role: "STUDENT" | "TEACHER" | "SUPER_ADMIN";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EndAssignmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AssignmentPeriodResponse"];
                };
            };
        };
    };
    reactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    issuePasswordResetCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OneTimeCodeResponse"];
                };
            };
        };
    };
    reissueActivationCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OneTimeCodeResponse"];
                };
            };
        };
    };
    assign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignProposalTeacherRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProposalAssignmentResponse"];
                };
            };
        };
    };
    end: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                office: "STUDENT_AFFAIRS_TEACHER" | "STUDENT_COUNCIL_PRESIDENT" | "STUDENT_COUNCIL_VICE_PRESIDENT";
                publicId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EndAssignmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AssignmentPeriodResponse"];
                };
            };
        };
    };
    appoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                office: "STUDENT_AFFAIRS_TEACHER" | "STUDENT_COUNCIL_PRESIDENT" | "STUDENT_COUNCIL_VICE_PRESIDENT";
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfficeAppointmentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AssignmentPeriodResponse"];
                };
            };
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API가 요청을 처리할 수 있음 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatusResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProposalDetailResponse"];
                };
            };
        };
    };
    reports: {
        parameters: {
            query?: {
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReportInboxItemResponse"][];
                };
            };
        };
    };
    cases: {
        parameters: {
            query?: {
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ModerationCaseResponse"][];
                };
            };
        };
    };
    caseDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ModerationCaseResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    csrf: {
        parameters: {
            query: {
                csrfToken: components["schemas"]["CsrfToken"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CsrfTokenResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                publicId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccountDetailResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                query?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AdminProposalSummaryResponse"][];
                };
            };
        };
    };
    teachers: {
        parameters: {
            query?: {
                query?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EligibleProposalTeacherResponse"][];
                };
            };
        };
    };
}
